services:
  arduino:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISPLAY:
    image: ghcr.io/anielsen001/arduino:latest
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/data:/data"
      - "$PWD:/opt/project"
    network_mode: "host"
    privileged: true
    command:
      - /bin/bash
    working_dir: /opt/project
